Building DAG of jobs...
Relative file path './config/mthfr.list' starts with './'. This is redundant and strongly discouraged. It can also lead to inconsistent results of the file-matching approach used by Snakemake. You can simply omit the './' for relative file paths.
Full Traceback (most recent call last):
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/__init__.py", line 730, in snakemake
    success = workflow.execute(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/workflow.py", line 736, in execute
    dag.init()
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 192, in init
    job = self.update([job], progress=progress, create_inventory=True)
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 881, in update
    raise exceptions[0]
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 839, in update
    self.update_(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 972, in update_
    raise ex
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 954, in update_
    selected_job = self.update(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 881, in update
    raise exceptions[0]
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 839, in update
    self.update_(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 972, in update_
    raise ex
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 954, in update_
    selected_job = self.update(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 881, in update
    raise exceptions[0]
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 839, in update
    self.update_(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 972, in update_
    raise ex
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 954, in update_
    selected_job = self.update(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 881, in update
    raise exceptions[0]
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 839, in update
    self.update_(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 972, in update_
    raise ex
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 954, in update_
    selected_job = self.update(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 881, in update
    raise exceptions[0]
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 839, in update
    self.update_(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 972, in update_
    raise ex
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 954, in update_
    selected_job = self.update(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 881, in update
    raise exceptions[0]
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 839, in update
    self.update_(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 972, in update_
    raise ex
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 954, in update_
    selected_job = self.update(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 881, in update
    raise exceptions[0]
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 839, in update
    self.update_(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 972, in update_
    raise ex
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 954, in update_
    selected_job = self.update(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 881, in update
    raise exceptions[0]
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 839, in update
    self.update_(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 972, in update_
    raise ex
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 954, in update_
    selected_job = self.update(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 881, in update
    raise exceptions[0]
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 839, in update
    self.update_(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 972, in update_
    raise ex
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 954, in update_
    selected_job = self.update(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 881, in update
    raise exceptions[0]
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 839, in update
    self.update_(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 972, in update_
    raise ex
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 954, in update_
    selected_job = self.update(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 881, in update
    raise exceptions[0]
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 839, in update
    self.update_(
  File "/home/ayla/anaconda3/envs/snakemake/lib/python3.8/site-packages/snakemake/dag.py", line 1000, in update_
    raise MissingInputException(job, missing_input)
snakemake.exceptions.MissingInputException: Missing input files for rule splitncigarreads:
    output: split/AAT001.A0101_ref.bam
    wildcards: sample=AAT001.A0101
    affected files:
        Homo_sapiens.GRCh38.113.chromosome.1.fa

MissingInputException in rule splitncigarreads in line 1 of /home/ayla/Dropbox/Ancient genotypes/DNA_variant_calling_GATK_Snakemake/workflow/rules/splitNcigar_ref.smk:
Missing input files for rule splitncigarreads:
    output: split/AAT001.A0101_ref.bam
    wildcards: sample=AAT001.A0101
    affected files:
        Homo_sapiens.GRCh38.113.chromosome.1.fa
